language: cpp
sudo: required
branches:
  except: "/pr\\/.*/"
matrix:
  include:
  - env: AUDI_BUILD="manylinux64Py36" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="manylinux64Py35" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="manylinux64Py34" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="manylinux64Py27" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
install:
- docker pull $DOCKER_IMAGE
script:
- mkdir build
- cd build
- bash ../tools/install_travis.sh
notifications:
  email: false
env:
  matrix:
    secure: VcnxeJY38v4btAXgVbP/YsF6acCb8qIu4HhSnm/YfYXKj7+mvqTK1JGXnrdjs6pkXRRqiLxeAPV2A04nZMq8TC8iigDhoogWwBCxsiTBNyxe94QfsJA5C9FXbeu/PjQ6xOxFekdXHsOsEw9xkxKJLY/oKs72yivq/CiS7BXJUejwF9n4kEBaGndzb/gmblJjye3gv43s9xwOa7vc4LFe9a3pRUbKwi649f++ZwObHXgaP49P6ReGByFjdFeqfXS0GWrj9zc449glzMbp3rtGSb9RWmMyRpdRhKhXpTtOLnMm3BI5miCmmDsLvlO8kecxDuxkNlv4Q0BmiglILrMX6R0UpK5+ReEhje/XrIva4Y3jEfJ/uA4i8ltVpEStNZQvmMELBj1ySEcvjuF899rcdsHgzncav+xIJI0DNtds60LkEL1BehV3Wb5LEkC3q3B+gUtAZbxOb+bJU1NggAkyHs7zf9EDHV7bn5rff7liW5/dLPM7kOGIe0W28FS5N2cJKc1nqWSlawmDtv3qzG78R2npzOboPeDxMPis3nzN1chGS5OFFtWOINgBgzn8niK+4YrEvI21n3p87beC1os7ESvA4RlFKqVIT3jjyrbWarTvfFSALFr7YtZDFGZ79tWMa+c1maPGM/IHlx638o7KMH+uEVRtzNPuaU3rHU//S4s=
