language: cpp
sudo: required

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

env:
  global:
    secure: BspqOXtCZ+Juy9Eg5TbTPZaS9GhYjxM9X2wRBJye2p32WZIQKgJGCSdzC7HyPZpclt2+pePbkFlsaSexPG0ovLqZ9QvAY4UsrFweOPTdVOlp1P8vc+h7qMYQmbq6zIt8u0uh39DhDjQXhmnUx9OY+lgWBHpFQXLIGwI3bvF5sRfrESFcSEjw7TgiYA7zKt4M+spBJW4Yxa4QBJyI2RJQ3SdBhRHIFbg3OjHIaGdwFpGVUY9PNF8jA+8RXIQu3LSxViXWIe/lufyCU5m4Fv5Cey/zNipnx2SndPKCi928IYAJjk5T6o3j5fGGd46gQdqyQ+hSM4V2/doSq0h8Y2RldxELGEnOGWkSivQtp7A+Q6hHiZeNfJ/A6ZnL5NpSxef+4myBXSaLqQyGzMgbujkbnzTDsQkC6Teg+gqSLqxmu1m1sVOenIkyu+NB8+m9gq9gbMMiX8vkz9Pu4ioDgBd7qH8txFXNwzaB+vjSICPm8iePCvg+MkxgR4igGPqU4bkzMj6KKKp1PLB28KZAPzJvAfWL3q+ag0p4Rn4yLOh+1Bbslo182wNsN7plCFksco01Nq0i4YlZMrGGh7jXb/o5K5WKR1YdS24HwuIT4q4Ct57hJwf/kyDgRYDbqTAg+fo9o3Q4A2ZaHMb0e1DvtGCUQHIWVi87MnbcXwm4FiiOAJo=


matrix:
  include:
    - env: AUDI_BUILD="manylinux64Py36" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
      sudo: required
      services:
      - docker
  #- sudo: required
  #  services:
  #  - docker
  #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE="Python35" PYTHON_VERSION="3.5"
  #    PATH_TO_PYTHON="/opt/python/cp35-cp35m"
  #- sudo: required
  #  services:
  #  - docker
  ##  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE="Python36" PYTHON_VERSION="3.6"
  #    PATH_TO_PYTHON="/opt/python/cp36-cp36m"

  #- sudo: required
  #  services:
  #  - docker
  #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE="Python27" PYTHON_VERSION="2.7"
  #   PATH_TO_PYTHON="/opt/python/cp27-cp27m"
  #- sudo: required
  #  services:
  #  - docker
  #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE="Python35" PYTHON_VERSION="3.5"
  #    PATH_TO_PYTHON="/opt/python/cp35-cp35m"
  #    PRE_CMD=linux32
  #- sudo: required
  #  services:
  #  - docker
  #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE="Python36" PYTHON_VERSION="3.6"
  #    PATH_TO_PYTHON="/opt/python/cp36-cp36m"
  #   PRE_CMD=linux32
  #- sudo: required
  #  services:
  #  - docker
  #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE="Python27" PYTHON_VERSION="2.7"
  #    PATH_TO_PYTHON="/opt/python/cp27-cp27m"
  #    PRE_CMD=linux32

install:
- docker pull $DOCKER_IMAGE

script:
    - mkdir build
    - cd build
    - bash ../tools/install_travis.sh

  

notifications:
  email: false
