language: cpp
sudo: required
branches:
  except: "/pr\\/.*/"

env:
  global:
    secure: "FuOCz1cdylY0Gi0OdbbeTPLp6JAzn+IvK0U0QaQccUgmiGVfg8qPBoKuDoerhgoS+cL0aiSP1RF1ku9l+Eig7VVC0sLALh1oCsNLnnoF1wbeoBI2lSJbb/W5xQqyHPcfi9luQaENL8Srf65n/fU4ivy8lEPUQzMgUseLN09oHNFres3KGJVa2h5ouj2a/q47tzpNn0BdUACA2VsjlKqxIEYNuQ/0o3GMwRKiOPOyrI8acLclWBvtZ1USt1ymZv/EU4jq5EPXIsWnW02i+J+oxIG8j7M95NXpMEiQugEnW3M4SjLfMKg5OzB+/cLHvypGBus/B8cz6nw3zMBI2OR7JwOkSKUMrsSaBXw6kob/YKxA36aPMPyyT74FvleLo7rfAcnvAXkPgWBP55WOVnGgZ2tJkyA80W98hc5nW7Py8mQtCQR01nZ1nXrAYID/nODCAE8qbPihPRMhliVPSIkABkj6mEQ1bBEGob3ybK4ogY0i5KgwlILu1v6tZz8J+iCzbQbL8DtAlVs32S6839EyVc+ocuzMKiapvdcov2hLxcR+JporCyw92PVhehrDUFfhqXanVVjWRePqLNUXHojT4RUxx5wI61jLnpRigB2R23tqJykxZozVfGse+st2Av+OgH9yUi3Eh8umahPY3NZcS984nC3ifd7XZrefQXFn3gs="
  
matrix:
  include:
  - env: AUDI_BUILD="manylinux64Py37" DOCKER_IMAGE="pagmo2/manylinux10_x86_64_with_deps"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="manylinux64Py36" DOCKER_IMAGE="pagmo2/manylinux10_x86_64_with_deps"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="manylinux64Py27" DOCKER_IMAGE="pagmo2/manylinux10_x86_64_with_deps"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="manylinux64Py27mu" DOCKER_IMAGE="pagmo2/manylinux10_x86_64_with_deps"
    sudo: required
    services:
    - docker
  - env: AUDI_BUILD="OSXDebug" AUDI_BUILD_TYPE="Debug"
    os: osx
    osx_image: xcode10.3
  - env: AUDI_BUILD="OSXRelease" AUDI_BUILD_TYPE="Release"
    os: osx
    osx_image: xcode10.3
# install:
# - docker pull $DOCKER_IMAGE
script:
  - if [[ "${AUDI_BUILD}" == OSX* ]]; then bash tools/travis_osx.sh; fi

notifications:
  email: false

