language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-6
    - g++-6
    - curl

matrix:
  include:
    #- compiler: gcc
    #  env: BUILD_TYPE="Release"
    #- compiler: gcc
    #  env: BUILD_TYPE="Debug"
    - compiler: gcc
      env: BUILD_TYPE="Python2"

install:
    - export AUDI_COMPILER=gcc;
      export CC=gcc-6;
      export CXX=g++-6;

script:
    - mkdir build
    - cd build
    - source ../tools/install_deps.sh
    - source ../tools/install_travis.sh
notifications:
  email: false
