language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-4.8
    - clang-3.8
    - graphviz
    - graphviz-dev
    - texlive
    - gcc-5
    - g++-5
    - gcc-6
    - g++-6
    - curl

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: gcc
      env: BUILD_TYPE="Debug"

script:
    - mkdir build
    - cd build
    - source ../tools/install_deps.sh
    - source ../tools/install_travis.sh
notifications:
  email: false
